language: javascript
os: osx
osx_image: xcode8.3
rvm: 2.4.1
branches:
  only:
  - master
cache:
  bundler: true
  yarn: true
  directories:
  - node_modules
  - vendor/bundle
before_install:
  - nvm install && nvm use
install:
  - npm install
  - bundle install
script:
  - npm run test-ci
  - npm run lint-check
after_success:
  - npm run update-coverage
  - bundle exec fastlane android deployAppetize
after_script:
  - bundle exec danger
env:
  - BUDDYBUILD_APP_ID=598eed55e1500b00013f26ed
  - APPETIZE_PUBLIC_KEY=nqak81nqbx3rh2hydcqbh5n47g
  global:
  - secure: hlSSf+COjkcF3YHSLakT0M+Qd8x7kMURnZssiNE1e/m201VKffKzOzI9g+1WO1G6H0FF1ggQCvZ6s/weugulZq5LR8BpowlJTDYwcNsocf/f9RWwIXwp3dyWelbTnHZxVcnOaDSV2BJGgiM67PorMxY+d9f0NvHsC9lKzXi8mZUb3dhSVPsuHR5hM8kZaURqo/YjV11/d7PHtvXu0T5XY5uFitxsEcAd+3/jkquyVolbbDNXwHJYrKveFXQ4lCt0CjyXdmRbN01GLJvKoEL6q2l0n48mcZYY17Kb/PhefA14yyqyLmMy+Hjvcjr0iTr1mHiOQ1qLaB2Hne2wl90J1T01eD/i73Nn53ZEP3K0Gluq99EchY9zUW1ZcroadBw/dlaD1UbbPi/Xl0B8Pnc5aYMZ7Nf2DRB4/oHqx8jvuHpLLFIKb21wvtmh5/cZjxZ2SR3Mdot7vYNso/yecvApspsglfbIrEeqe4zAzpEzqMyC6MhxQTLxbiJTBvkDzgxa3q2QLtO59G1qOM72KIiapTVdwIMxIKj0xcg1QSzjULKuh/qlk/NOOawZS1vEJu7V+sltBwUVmEXMdr7jqGA14W/EXbX9WMr4KihhFNgmvXb73y3VuXkLnH/ib912z01BFaeU6S5UuoXfR3Z1gz7VTgbJtEystCnsSYi8zxMzdQI=
  - secure: jpdhaUOlUDmGAe59u3UVR1JF2qN3nPgNmdqVsNpqq37Eawtd77O+Wwzpr909AAy7rbv8xn3uLgSJbxMrKVzxyPEhg8vmiayqAAy/VKA686BmfVpmY6JJOjefv8oAGM+lm653hAmekz5OaxrUKzxS9UNJPB/Ja/C7UWZ+OIOn/zJHITy/OrVTkw3PFPgEfJxhBNF78gfrWna+TE7bConmZk3Y0bCIPtEtPWITJVd0y548/cOICuM8eid4no3QOX4uDdzIBVJ8BRl9zroNEwoGqJGjX6P8r4h9Ax7GqX8AABC0vQszWAvLcDBC8OvL5mBCm+GM1+d8ns3liVpFhZxNGgHo6wPy/YjHD41RHoN07XkMg1CSLzQzG2q44IuWuWFbQFaCGw/HbET/qLkT2ybWI3h87vEkX3mRi9JhsaRtRc1q5gWwdiROoB1AoT+vmMdAwnqn7Gqw21J7BmRbG6KFGYi5L5RHD1I2BUOebcQe5bB4B6KTAkT1mI5C1V4rnzjf4DB/J55lePDcururOM4t4zGvFt5Ov4tVsTLrOi6fkuO68JAsbVrD6mZCEW2W0g2hIBjdfdQyISE2Xr+NaIUNfhlNQ4FEal6lTx8ziSUGoC5ROaqVIhLecdghcx7NEbX/YbMwldNWe95d61f5powDd2/taBeFG3kuJkrQqq7M0Xs=
  - secure: hxcBcnsR8siKK7293acQGK1Nqbv/HhD2m8geCFNe0a1mLAFSagrxzIAq0iVsG2EQrJBKzGqAIXadrAxSzqRuhTnE24nkn4yb+PwXYV8dXuEw2kVOUP0gibZQzHgIXx7/uobxx6tioHufVdSojwv9HOmQf9gY+6Dchte5DW27/PJZdrKFp35BDbDb+4L4mDQV0u8rWCL/xEoBuVr1bXIKbE3teePL4aGMiIOMip61g0v7BAv5EcCzDtftkT8nZYru45gKeuHV+DF2Iw/iYDPaqT70xPaIPTjKavvtnXDulmrQR1o7bqwML/qEPppHj6uK0iNmoX3WMoKN2+8la69ZwNMDQTPSDH9ej+jOuyCn6nk4QdcTsbIi1VyCWKM48b9wd+EP47CUkr3oTXhBU22O3OX/qyCWCl6xzY/Xh42c9n3lk+YsAxCeuUnnHWMp3SueKTRhAzNMiEqTAZdiuzw3JZWPGkAckbYrhyeyfjxPNAmLyhRyuzCLHRJfC2aoi6ar/oskEEdG1TXNA00Fi/X6Kwu4kNUl5F+apty/vwiXa8LnUgYNpnYlTMrWrf/Ere7IlxvB/B345HAKDlqF5CN7ir3O668hIC5tEnsUnvXAFS+gkeYiO/TFkKHjZ7jNgE0jkyzr3XCtAlkN5CApDgqVNjUnI9Vvq15BHdJPDjtdJcI=
  - secure: xbHDnMwJFzEB+jA+Cf1MmkinN6lGxavteAD5e2O0Ys9FF1ly7E1sYBsk1aEgSkitpRLpm2s24JtY+3bptqHAyGGG8YuCRUbTUyuw2SiiV2ZmfzdT2qzT3f+60VuA2+jh+jG4vsPYPqi3LnWpV2ATcCJA+s2CB3V8LVnX63TvBAK0n0m6L1FkGITxUFjJUmNpMYyN0zU34ft27CmqXPKx9x+utKxjmIorut5ggGTw47QdiZ7bqlb8g+nirhO59M6+SwlmyVdk2EDNO6xKRvjb8ty8rU+yqcZ5XP1uoky0ll0ySSUzg5IFQUbtM6I9WMvirMxUr8REX8YAeaPLfYZiT3XhJHvXxKNE/T2sL3e+aj0BlYf2ckNs+IiI+vle9xZQKpvIwMMhz+o0teds8YLkr5Fyar6++kfdiPa34NbSEQCmNhwhCUqtCfnH0f4J/shDMgZX1C7g7FuxwiFXPaaKjk71KArTcW21cI2sKATyfQD/BMhqWFCM8ZYFeM4Qy/eMZGthgsOVe1ZdGGRT83Mnn5nNMWIXZNc5OAZzvSKC4QMJlte3JCulzByqyB6HYM03/OGplb30mHIy4q4KQhjS8dEp2oIaAhx3EDF87Ldxi6sxUpuHkQcEFkHgXIFdfSyWDhONY3FMZNFF/gM7jx0IlwcWw4vQD4vvsr2v+MnIs8g=
  - secure: WgrSHJ2N8MTJPA/VgHG1PnPOz023g3wSrw7j2k6KX3M++cLKenA8vWuYhFsShRmx4sZY1AUvGwcXrgXqwNamegvg674m5Jk0w5cAUTtBS8bEf0G/E1xsUZ1Cjuyz5vuwu7bp0fLQnwMU0i/ps4A9JN8tBLXAGBITtXSrCCka8hxixLS8NeUo8AJmbX0jkgA96obGozPx9fUY0DsLy5UraCMxtan1PMpMaaJJlds+4PqpOqKJzHonR+eCQ0QbXAoyb8VFuldhPuIZGK9O9XGkZhCJnUmQU/MoF28NlOa+pamOet/naJc7Gxa4J+XVwFbgdqfmpPlD/9jVIa84SRu9URDJQmmFcfCIeWRitCsjFg+YYqhKcCCjL1a6iSadibh/1OIO5jndqzlaUvKHULJ/Icc9sph3P/MYY3pxZ+7D6wNEmwNtZNXYzKq6yO2imfxUWcADOaVUbP1a3amemqZlPvjxXLgFabK725vRSg5b1/BEFkNkag4v/t+bxUXC9qgOgMSjEq313vP8if/WBUJy6ljYwrC/hfKQoiGGJSvnTFxC+23eZ32ySZpbkgyG8EYdMksInV+btTAkS2Sn1JfYXy9TteEm6I16wWS2uHjqr0da7Oyq0ysF0QVU5uR7yafJVoI0yjCX9xUADcohG0Bwldb5vCW56Dr+FAb0MelIol4=
