// flow-typed signature: 583768a22c39a755032a4acef444763d
// flow-typed version: <<STUB>>/immutable_v^2.2.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'immutable' {
  declare module.exports: any;
}
