// flow-typed signature: 6e230201b09dd71fb4793cc2378f84fc
// flow-typed version: <<STUB>>/nachos-ui_v^0.1.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nachos-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nachos-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nachos-ui/lib/Badge' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/Bubble' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/Button' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/Card' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/Carousel' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/Checkbox' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/Gravatar' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/index' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/Indicator' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/Input' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/Progress' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/Radio' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/RadioGroup' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/SegmentedControlButton' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/Slider' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/Spinner' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/Switcher' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/TabButton' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/themeManager' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/typography/A' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/typography/B' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/typography/Em' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/typography/H1' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/typography/H2' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/typography/H3' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/typography/H4' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/typography/H5' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/typography/H6' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/typography/I' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/typography/P' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/typography/Strong' {
  declare module.exports: any;
}

declare module 'nachos-ui/lib/typography/Text' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nachos-ui/lib/Badge.js' {
  declare module.exports: $Exports<'nachos-ui/lib/Badge'>;
}
declare module 'nachos-ui/lib/Bubble.js' {
  declare module.exports: $Exports<'nachos-ui/lib/Bubble'>;
}
declare module 'nachos-ui/lib/Button.js' {
  declare module.exports: $Exports<'nachos-ui/lib/Button'>;
}
declare module 'nachos-ui/lib/Card.js' {
  declare module.exports: $Exports<'nachos-ui/lib/Card'>;
}
declare module 'nachos-ui/lib/Carousel.js' {
  declare module.exports: $Exports<'nachos-ui/lib/Carousel'>;
}
declare module 'nachos-ui/lib/Checkbox.js' {
  declare module.exports: $Exports<'nachos-ui/lib/Checkbox'>;
}
declare module 'nachos-ui/lib/Gravatar.js' {
  declare module.exports: $Exports<'nachos-ui/lib/Gravatar'>;
}
declare module 'nachos-ui/lib/index.js' {
  declare module.exports: $Exports<'nachos-ui/lib/index'>;
}
declare module 'nachos-ui/lib/Indicator.js' {
  declare module.exports: $Exports<'nachos-ui/lib/Indicator'>;
}
declare module 'nachos-ui/lib/Input.js' {
  declare module.exports: $Exports<'nachos-ui/lib/Input'>;
}
declare module 'nachos-ui/lib/Progress.js' {
  declare module.exports: $Exports<'nachos-ui/lib/Progress'>;
}
declare module 'nachos-ui/lib/Radio.js' {
  declare module.exports: $Exports<'nachos-ui/lib/Radio'>;
}
declare module 'nachos-ui/lib/RadioGroup.js' {
  declare module.exports: $Exports<'nachos-ui/lib/RadioGroup'>;
}
declare module 'nachos-ui/lib/SegmentedControlButton.js' {
  declare module.exports: $Exports<'nachos-ui/lib/SegmentedControlButton'>;
}
declare module 'nachos-ui/lib/Slider.js' {
  declare module.exports: $Exports<'nachos-ui/lib/Slider'>;
}
declare module 'nachos-ui/lib/Spinner.js' {
  declare module.exports: $Exports<'nachos-ui/lib/Spinner'>;
}
declare module 'nachos-ui/lib/Switcher.js' {
  declare module.exports: $Exports<'nachos-ui/lib/Switcher'>;
}
declare module 'nachos-ui/lib/TabButton.js' {
  declare module.exports: $Exports<'nachos-ui/lib/TabButton'>;
}
declare module 'nachos-ui/lib/themeManager.js' {
  declare module.exports: $Exports<'nachos-ui/lib/themeManager'>;
}
declare module 'nachos-ui/lib/typography/A.js' {
  declare module.exports: $Exports<'nachos-ui/lib/typography/A'>;
}
declare module 'nachos-ui/lib/typography/B.js' {
  declare module.exports: $Exports<'nachos-ui/lib/typography/B'>;
}
declare module 'nachos-ui/lib/typography/Em.js' {
  declare module.exports: $Exports<'nachos-ui/lib/typography/Em'>;
}
declare module 'nachos-ui/lib/typography/H1.js' {
  declare module.exports: $Exports<'nachos-ui/lib/typography/H1'>;
}
declare module 'nachos-ui/lib/typography/H2.js' {
  declare module.exports: $Exports<'nachos-ui/lib/typography/H2'>;
}
declare module 'nachos-ui/lib/typography/H3.js' {
  declare module.exports: $Exports<'nachos-ui/lib/typography/H3'>;
}
declare module 'nachos-ui/lib/typography/H4.js' {
  declare module.exports: $Exports<'nachos-ui/lib/typography/H4'>;
}
declare module 'nachos-ui/lib/typography/H5.js' {
  declare module.exports: $Exports<'nachos-ui/lib/typography/H5'>;
}
declare module 'nachos-ui/lib/typography/H6.js' {
  declare module.exports: $Exports<'nachos-ui/lib/typography/H6'>;
}
declare module 'nachos-ui/lib/typography/I.js' {
  declare module.exports: $Exports<'nachos-ui/lib/typography/I'>;
}
declare module 'nachos-ui/lib/typography/P.js' {
  declare module.exports: $Exports<'nachos-ui/lib/typography/P'>;
}
declare module 'nachos-ui/lib/typography/Strong.js' {
  declare module.exports: $Exports<'nachos-ui/lib/typography/Strong'>;
}
declare module 'nachos-ui/lib/typography/Text.js' {
  declare module.exports: $Exports<'nachos-ui/lib/typography/Text'>;
}
