// flow-typed signature: 1f0ebd6739339e24c4645e7cb085521d
// flow-typed version: <<STUB>>/react-native-config_v0.6.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-config/index' {
  declare module.exports: $Exports<'react-native-config'>;
}
declare module 'react-native-config/index.js' {
  declare module.exports: $Exports<'react-native-config'>;
}
